version: "3.9"

services:
  github-app:
    container_name: github-webhook
    restart: unless-stopped
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: go run main.go
    environment:
      - APP_ENV=development
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
