version: "3.9"

services:
  github-app:
    container_name: github-webhook
    restart: unless-stopped
    depends_on:
      - db
    build:
      context: ./webhook-server
      dockerfile: Dockerfile
    volumes:
      - ./webhook-server:/app
    command: go run main.go
    environment:
      - APP_ENV=development
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.23.13
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
volumes:
  weaviate_data:
