FROM golang:1.22.0 as build-stage
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /github-app

FROM gcr.io/distroless/base-debian11 AS build-release-stage
WORKDIR /
COPY --from=build-stage /github-app /github-app
EXPOSE 8080
ENTRYPOINT [ "/github-app" ]
